---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: venom-cars-lab
# namePrefix: venom-cars-lab-

resources:
  - github.com/redhat-partner-solutions/vse-ocp-bases/base/sno?ref=main

patchesStrategicMerge:
  - ./patches/nmstate-config.yaml
  - ./patches/aci.yaml

patches:
  - target:
      version: v1
      kind: Namespace
    patch: |-
      - op: replace
        path: /metadata/labels/name
        value: 'venom-cars-lab'
  - target:
      kind: AgentClusterInstall
    patch: |-
      - op: replace
        path: /spec/clusterDeploymentRef/name
        value: 'venom-cars-lab'
      - op: replace
        path: /metadata/name
        value: 'venom-cars-lab'
  - target:
      kind: SealedSecret
    patch: |-
      - op: replace
        path: /spec/template/metadata/namespace
        value: 'venom-cars-lab'
  - target:
      kind: Secret
    patch: |-
      - op: replace
        path: /metadata/name
        value: 'venom-cars-lab-bmc-super1'
  - target:
      kind: ManagedCluster
    patch: |-
      - op: replace
        path: /metadata/name
        value: 'venom-cars-lab'
  - target:
      kind: BareMetalHost
    path: ./patches/bmh-venom-cars-lab-super1-patch.yaml
  - target:
      kind: ClusterDeployment
    path: ./patches/clusterdeployment-patch.yaml
  - target:
      kind: InfraEnv
    path: ./patches/infraenv-patch.yaml
  - target:
      kind: KlusterletAddonConfig
    path: ./patches/klusterletaddon-patch.yaml
