apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: replace-sealed-secrets-secret
  namespace: sealed-secrets
rules:
  - apiGroups: [extensions]
    resources:
      - secrets
      - pods
      - deployments
    verbs:
      - get
      - list
      - delete
      - create