apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: replace-sealed-secrets-secret
  namespace: sealed-secrets
rules:
  - apiGroups: [""]
    resources:
      - secrets
      - pods
    verbs:
      - get
      - list
      - delete
      - create