apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: managed-secrets
  namespace: sealed-secrets
rules:
  - apiGroups: [""]
    resources:
      - secrets
    verbs:
      - get
      - delete
      - create