---
apiVersion: agent-install.openshift.io/v1beta1
kind: NMStateConfig
metadata:
  name: nmstate-super1
  labels:
    cluster-name: yukon-nmstate
spec:
  config:
    interfaces:
      - name: bondctrlplane
        type: bond
        mac-address: "b4:96:91:c8:a2:7c"
        state: up
        ipv4:
          enabled: true
          address:
            - ip: 192.168.38.24
              prefix-length: 26
          dhcp: false
        #ipv6:
        #  enabled: true
        #  address:
        #  - ip: fd00:6:6:2052::101
        #    prefix-length: 64
        #  autoconf: false
        #  dhcp: false
        link-aggregation:
          mode: 802.3ad
          options:
            lacp_rate: "fast"
          port:
            - eno12399
            - eno12409
    dns-resolver:
      config:
        server:
          - 192.168.38.12
          #- fd00:6:6:11::52
    routes:
      config:
        - destination: 0.0.0.0/0
          next-hop-address: 192.168.38.1
          next-hop-interface: bondctrlplane
        #- destination: ::/0
        #  next-hop-address: fd00:6:6:2052::1
        #  next-hop-interface: bond0
  interfaces:
    - name: eno12399
      macAddress: b4:96:91:c8:a2:7c
    - name: eno12409
      macAddress: b4:96:91:c8:a2:7d
---
apiVersion: agent-install.openshift.io/v1beta1
kind: NMStateConfig
metadata:
  name: nmstate-super2
  labels:
    cluster-name: yukon-nmstate
spec:
  config:
    interfaces:
      - name: bondctrlplane
        type: bond
        mac-address: "b4:96:91:c8:a2:c4"
        state: up
        ipv4:
          enabled: true
          address:
            - ip: 192.168.38.25
              prefix-length: 26
          dhcp: false
        #ipv6:
        #  enabled: true
        #  address:
        #  - ip: fd00:6:6:2052::102
        #    prefix-length: 64
        #  autoconf: false
        #  dhcp: false
        link-aggregation:
          mode: 802.3ad
          options:
            lacp_rate: "fast"
          port:
            - eno12399
            - eno12409
    dns-resolver:
      config:
        server:
          - 192.168.38.12
          #- fd00:6:6:11::52
    routes:
      config:
        - destination: 0.0.0.0/0
          next-hop-address: 192.168.38.1
          next-hop-interface: bondctrlplane
        #- destination: ::/0
        #  next-hop-address: fd00:6:6:2052::1
        #  next-hop-interface: bond0
  interfaces:
    - name: eno12399
      macAddress: b4:96:91:c8:a2:c4
    - name: eno12409
      macAddress: b4:96:91:c8:a2:c5
---
apiVersion: agent-install.openshift.io/v1beta1
kind: NMStateConfig
metadata:
  name: nmstate-super3
  labels:
    cluster-name: yukon-nmstate
spec:
  config:
    interfaces:
      - name: bondctrlplane
        type: bond
        mac-address: "b4:96:91:c8:a1:d0"
        state: up
        ipv4:
          enabled: true
          address:
            - ip: 192.168.38.26
              prefix-length: 26
          dhcp: false
        #ipv6:
        #  enabled: true
        #  address:
        #  - ip: fd00:6:6:2052::103
        #    prefix-length: 64
        #  autoconf: false
        #  dhcp: false
        link-aggregation:
          mode: 802.3ad
          options:
            lacp_rate: "fast"
          port:
            - eno12399
            - eno12409
    dns-resolver:
      config:
        server:
          - 192.168.38.12
          #- fd00:6:6:11::52
    routes:
      config:
        - destination: 0.0.0.0/0
          next-hop-address: 192.168.38.1
          next-hop-interface: bondctrlplane
        #- destination: ::/0
        #  next-hop-address: fd00:6:6:2052::1
        #  next-hop-interface: bond0
  interfaces:
    - name: eno12399
      macAddress: b4:96:91:c8:a1:d0
    - name: eno12409
      macAddress: b4:96:91:c8:a1:d1
